/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbmsdemo;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.Dictionary;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JMenuItem;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import utils.GlobalData;

/**
 *
 * @author Pham Van Vung
 */
public class FrmMain extends javax.swing.JFrame {
    JMenuItem[] menuItems;
    //Declare all the forms
    FrmLogin frmLogin = new FrmLogin();
    FrmAddStudent frmAddStudent = new FrmAddStudent();
    FrmViewStudents frmViewStudents = new FrmViewStudents();
    //Create a map for all the forms
    Map<String, JInternalFrame> forms = new HashMap<>();
    
    
    
    /**
     * Creates new form JavaApplication18
     */
    public FrmMain() {
        initComponents();
        //Add the forms to the container
        forms.put("frmLogin", frmLogin);
        forms.put("frmAddStudent", frmAddStudent);
        forms.put("frmViewStudents", frmViewStudents);
        //Add them to the container
        forms.keySet().forEach(key->{
            jdpContainer.add(forms.get(key));
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jdpContainer = new javax.swing.JDesktopPane();
        mnbMainMenu = new javax.swing.JMenuBar();
        mniFile = new javax.swing.JMenu();
        mniLogin = new javax.swing.JMenuItem();
        mniLogout = new javax.swing.JMenuItem();
        mniExit = new javax.swing.JMenuItem();
        mniWindows = new javax.swing.JMenu();
        mnuStudent = new javax.swing.JMenu();
        mniAddStudent = new javax.swing.JMenuItem();
        mniUpdateStudent = new javax.swing.JMenuItem();
        mniDeleteStudent = new javax.swing.JMenuItem();
        mniViewStudent = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpContainer.setName("jdpContainer"); // NOI18N

        javax.swing.GroupLayout jdpContainerLayout = new javax.swing.GroupLayout(jdpContainer);
        jdpContainer.setLayout(jdpContainerLayout);
        jdpContainerLayout.setHorizontalGroup(
            jdpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        jdpContainerLayout.setVerticalGroup(
            jdpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        getContentPane().add(jdpContainer, java.awt.BorderLayout.CENTER);

        mniFile.setText("File");

        mniLogin.setText("login...");
        mniLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLoginActionPerformed(evt);
            }
        });
        mniFile.add(mniLogin);

        mniLogout.setText("logout");
        mniFile.add(mniLogout);

        mniExit.setText("exit");
        mniFile.add(mniExit);

        mnbMainMenu.add(mniFile);

        mniWindows.setText("Manage");

        mnuStudent.setText("Student");

        mniAddStudent.setText("Add");
        mniAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddStudentActionPerformed(evt);
            }
        });
        mnuStudent.add(mniAddStudent);

        mniUpdateStudent.setText("Update");
        mniUpdateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUpdateStudentActionPerformed(evt);
            }
        });
        mnuStudent.add(mniUpdateStudent);

        mniDeleteStudent.setText("Delete");
        mniDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDeleteStudentActionPerformed(evt);
            }
        });
        mnuStudent.add(mniDeleteStudent);

        mniViewStudent.setText("View");
        mniViewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewStudentActionPerformed(evt);
            }
        });
        mnuStudent.add(mniViewStudent);

        mniWindows.add(mnuStudent);

        mnbMainMenu.add(mniWindows);

        setJMenuBar(mnbMainMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLoginActionPerformed
        showForm("frmLogin", false);
    }//GEN-LAST:event_mniLoginActionPerformed

    
    private void showForm(String frmName) {
        showForm(frmName, false);
    }
    private void showForm(String name, boolean checkLogin){
        if (checkLogin && GlobalData.stf == null) {
            showForm("frmLogin", false);
        } else {
            try {
                if (forms.get(name).isClosed()) {
                    forms.put(name,forms.get(name).getClass().newInstance());
                    jdpContainer.add(forms.get(name));
                }
                forms.get(name).show();
                forms.get(name).setSelected(true);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }
    

    private void mniDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDeleteStudentActionPerformed
        showForm("frmViewStudents");
    }//GEN-LAST:event_mniDeleteStudentActionPerformed
    
    private void mniAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddStudentActionPerformed
        showForm("frmAddStudent");
    }//GEN-LAST:event_mniAddStudentActionPerformed

    private void mniViewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewStudentActionPerformed
        showForm("frmViewStudents");
    }//GEN-LAST:event_mniViewStudentActionPerformed

    private void mniUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUpdateStudentActionPerformed
        showForm("frmViewStudents");
    }//GEN-LAST:event_mniUpdateStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmMain ja
                        = new FrmMain();
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                ja.setSize(dim);
                ja.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDesktopPane jdpContainer;
    private javax.swing.JMenuBar mnbMainMenu;
    private javax.swing.JMenuItem mniAddStudent;
    private javax.swing.JMenuItem mniDeleteStudent;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenu mniFile;
    private javax.swing.JMenuItem mniLogin;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JMenuItem mniUpdateStudent;
    private javax.swing.JMenuItem mniViewStudent;
    private javax.swing.JMenu mniWindows;
    private javax.swing.JMenu mnuStudent;
    // End of variables declaration//GEN-END:variables
}
